config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  get 'search' => 'searchs#seach'
  # チャット機能
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  # フォロー機能
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  resources :users do
    get :follow, on: :member
    get :follower, on: :member
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, length: { in: 1..200 }
  belongs_to :user

  is_impressionable #PV数

  # カウント
  has_many :view_counts, dependent: :destroy
  # フォロー機能
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  # コメント機能
  has_many :book_comments, dependent: :destroy
  
  # いいね機能
  has_many :favorites, dependent: :destroy

  # 検索機能
    def self.looks(searches, words)
      if searches == "perfect_match"
        @book = Book.where("title LIKE?","#{words}")
      elsif searches == "forward_match"
        @book = Book.where("title LIKE?","#{words}%")
      elsif searches == "backward_match"
        @book = Book.where("title LIKE?","%#{words}")
      elsif searches == "partial_match"
        @book = Book.where("title LIKE?","%#{words}%")
      else
        @book = Book.all
      end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness:true, length: {in: 2..20}
  validates :introduction,length: { maximum: 50}


  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  #カウント  
  has_many :view_counts, dependent: :destroy

  # コメント機能
  has_many :book_comments, dependent: :destroy

  # チャット機能
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  # フォロー機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
    # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def matchers
    follower & followed
  end

  # いいね機能
  has_many :favorites, dependent: :destroy

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  # 検索機能
  def self.looks(searches, word)
    if searches == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif searches == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif searches == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :editing_user, only: [:edit]
  impressionist :actions=> [:show]

  def new
    @book = Book.new
  end

  def create
    @booknew = Book.new(book_params) 
    @booknew.user_id =  current_user.id 
    @user = current_user
  if @booknew.save 
    redirect_to book_path(@booknew.id), notice: 'Book was successfully created'  
  else
    @books = Book.all
    render :index
  end
end

  def index
    @books = Book.all
    @booknew = Book.new
    @user = current_user

  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    impressionist(@book, nil, unique: [:ip_address])
    @user = @book.user
    # @user = User.find(@book.user_id)
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated!'
    else
      
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def editing_user
    book = Book.find(params[:id])
    if book.user != current_user 
      redirect_to books_path
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
      @chats = @room.chats 
      @chat = Chat.new(room_id: @room.id)
    end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
aaaaaaaaaaaaaaaaaaaaaaaaa
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  
  def follow
    @user = User.find(params[:id])
    @users = @user.follower
  end
  
  def follower
    @user = User.find(params[:id])
    @users = @user.followed
  end

  def index
    @user = current_user
    @users = User.all
    @booknew = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @booknew = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
  else
    redirect_to user_path(current_user)
  end
end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id),notice: 'Book was successfully updated!'
    else
      render :edit
  end
end

private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_commnets_helper.rb
module BookCommnetsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_comment.html.erb
<table class="table table-hover table-invers">
  <thead>
      <th>コメント投稿者</th>
        <th>コメント内容</th>
          <th colspan="2"></th>
            <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td><%= link_to user_path(book_comment.user) do %>
                <%= attachment_image_tag book_comment.user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg" %><br>
                <%= book_comment.user.name  %>
              <% end %>
              </td>
              <td><%= book_comment.comment %></td>
                <td><% if book_comment.user_id == current_user.id %>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book.id, book_comment.id), class: 'btn-sm btn-danger',method: :delete, remote: true%>
                  <% end %>
                </td>
              <td class="comment-date pull-right">
                <%= book_comment.created_at.strftime('%Y/%m/%d') %>
              </td>
              </tr>
            <% end %>
          </table>
        </div>
      </tr>
    </thead>
  </tbody>
</table>

app/views/books/_error.html.erb
    <p id="notice"></p>
    <% if model.errors.any? %>
  <div id="error_explanation">
    <h3 class="text-danger"><%= pluralize(model.errors.count,"error") %> prohibited this product from being saved:</h3>

  <ul><% model.errors.full_messages.each do |message| %>
    <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
</div>
    <% end %>

app/views/books/_form.html.erb
    <h2 class="mt-3">New book</h2>
      <%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class:"form-control book_body" %>
  </div>

  <div class="form-group">
    <%= f.submit btn, class:"btn btn-success col-xs-12" %>
  </div>
  <% end %>

app/views/books/_index.html.erb
    <table class="table table-hover table-invers">
      <thead>
        <th></th>
          <th>title</th>
            <th>opinion</th>
              <th colspan="3"></th>
                <% @books.each do |book| %>
                <tr><td>
                    <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, size: "50x50",fallback: "no_image.jpg"%>
                    <% end %></td>
                    <td><%= link_to book.title, book_path(book.id) %></td>
                    <td><%= book.body %></td>
                    <td id="favorite_buttons_<%= book.id %>">
                      <%= render 'favorites/favorite', book: book %>
                    </td>
                    <td><%= "コメント：#{book.book_comments.count}" %></td>
                    <td><%=  "閲覧数: #{book.impressionist_count}" %></td>
                </tr>
              <% end %>
            </table>
          </div>
        </tr>
      </thead>
    </tbody>
  </table>

app/views/books/edit.html.erb
<div class='container'>
  <%= render 'books/error', model: @book %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
    <table>
          <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class:"form-control" %>
        </div>

        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit btn: "Update Book", class:"btn btn-success col-xs-12" %>
        </div>
            <% end %>
        <td class="show"><%= link_to "Show", book_path(@book.id) %></td>
        <td>|</td>
        <td class="back"><%= link_to "Back", books_path %></td>
    </table>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>

<div class='container px-5 px-sm-0'>
<%= render 'books/error', model: @booknew %>
    <div class='row'>
        <div class='col-md-3'>
            <table class='table'>
                <%= render 'users/profile', user: @user %>
            </table>
                
            <div>
                <%= render 'books/form', {book: @booknew, btn: 'Create Book'} %>
            </div>
        </div>
            <div class='col-md-8 offset-md-1'>
                <h2>Books</h2>
                <%= render 'books/index', book: @books %>
                
            </div>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <table class='table'>
          <%= render 'users/profile', user: @user %>
      </table>

        <div>
          <tr><%= render 'books/form', {book:@booknew, btn: 'Create Book'} %></tr>
        </div>
    </div>
    <div class='col-md-8 offset-md-1'>
      <table class="table table-user-show">
        <tr>
        <h2>Book detail</h2>
        <tbody>
        </tr>
        <td><%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg"%><br>
            <% end %>
            <%= link_to @user.name, user_path(@user) %>
        </td>
        <td><%= link_to @book.title %></td>
        <td><%= @book.body %></td>
        <td id="favorite_buttons_<%= @book.id %>">
          <%= render 'favorites/favorite', book: @book %>
        </td>
        <td><%= "コメント数:#{@book.book_comments.count}" %></td>
        <td><%=  "閲覧数: #{@book.impressionist_count}" %></td>
        <% if @book.user_id == current_user.id %>
        <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", book_path, method: :delete, class:"btn btn-sm btn-danger", "data-confirm"=> "Are you sure?" %></td>
            <% end %>
        </tr>
        </tbody>
      </table>
        <%# コメント機能 %>
        <div>
          <%= render 'book_comments/form', book:@book, book_comment: @book_comment %>
        </div>
        <div id="comments_area_<%= @book.id %>">
          <%= render partial: 'books/comment', local: {book_comment: @book_comment} %>
      </div>
    </div>
  </div>
</div>

app/views/chats/_chat_button.html.erb
<% if current_user != @user %>
  <%= link_to 'チャットする', chat_path(@user.id) %>
<% end %> 

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-xs-6">
          <h2 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>"><%= @user.name %> さんとのチャット</h2>

            <table class="message table">
              <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.name %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.name %></th>
                </tr>
              </thead>
              <% @chats.each do |chat| %>
                <% if chat.user_id == current_user.id %>
                <tbody>
                  <tr>
                    <th>
                      <p style="text-align: left;"><%= chat.message %></p>
                    </th>
                    <th></th>
                  </tr>
                </tbody>
                <% else %>
                <tbody>
                  <tr>
                    <th></th>
                    <th>
                      <p style="text-align: right;"><%= chat.message %></p>
                    </th>
                  </tr>
                </tbody>
                <% end %>
              <% end %>
            </table>
            <%= form_with model: @chat do |f| %>
            <%= f.text_field :message, :placeholder => "メッセージを入力して下さい" , :size => 30 %>
            <%= f.hidden_field :room_id %>
            <%= f.submit "投稿する" %>
          <% end %>
        </div>
    </div>
</div>

      

app/views/users/_index.html.erb
<table class="table table-hover table-inverse">
<thead>
<tr>
  <th>image</th>
  <th>name</th>
  <th colspan="4"></th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
  <td><%= attachment_image_tag user, :profile_image, size: "40x40",fallback: "no_image.jpg" %></td>
  <td><%= user.name %></td>
  <td><%= "フォロー数:#{user.follower.count}" %></td>
  <td><%= "フォロワー数:#{user.followed.count}" %></td>
  <td>
    <% unless current_user == user %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
  </td>
  <% end %>
    <td><%= link_to "Show", "/users/#{user.id}" %></td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/users/_profile.html.erb
<table class="table table-user">
  <h2>User info</h2>
		<tr><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg"%></tr>
		<tr>
		  <th>name</th>
		  <th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th><%= "follow" %></th>
			<th><%= link_to "#{user.follower.count}", follow_user_path(user.id) %></th>
		</tr>
		<tr>
			<th><%= "follower" %></th>
			<th><%= link_to "#{user.followed.count}", follower_user_path(user.id) %></th>
		</tr>
</table>

				<% unless current_user == user %>
					<% if current_user.following?(user) %>
						<%= link_to 'Unfollow', unfollow_path(user.id), method: :POST, class: 'btn btn-outline-danger' %>
					<% else %>
						<%= link_to 'Follow', follow_path(user.id), method: :POST, class: 'btn btn-outline-primary' %>
					<% end %>
				<% end %>
			<% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
			<%= render 'chats/chat_button' %> <%# チャットボタン  %>
			<% end %>
		<div class="row mt-3">
			<%= link_to " ", edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
		</div>
<%# 編集ボタンについて %>
<%# <% if user.id == current_user.id %> 
<%# <% else %>
<%# <td><%= link_to " ", user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
<%# <% end %>

app/views/users/edit.html.erb
  <div class="container">
          <p id="notice"></p>
        <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3 class="text-danger"><%= pluralize(@user.errors.count,"error") %> prohibited this product from being saved:</h3>
        <ul><% @user.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
        <% end %>
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
          <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
              <label>name</label>
              <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="form-group">
                <label>Image</label>
                <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:"form-control-file user_image" %>
          </div>
          <div class="form-group">
              <label>introduction</label>
              <%= f.text_area :introduction, class:"form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
            <% end %>
          </div>
      </div>
    </div>
  </div>

app/views/users/follow.html.erb
<p id="notice"></p>
<div class='col-md-10 offset-md-1'>
  <h3>Follow Users</h3>
    <% if @users.empty? %>
        <span>ユーザーはいません</span>
    <% else %>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th colspan="4"></th>
        </tr>
      </thead>
        <tbody>
            <% @user.following_user.where.not(id: current_user.id).each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg" , size:"40x40" %></td>
            <td><%= "#{user.name}" %></td>
            <td><%="フォロー数:#{user.follower.count}" %></td>
            <td><%= "フォロワー数:#{user.followed.count}" %></td>
            <td><%= link_to "show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/follower.html.erb
<p id="notice"></p>
<div class='col-md'>
  <h3>Follower Users</h3>
    <% if @users.empty? %>
        <span>ユーザーはいません</span>
    <% else %>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th colspan="4"></th>
        </tr>
      </thead>
        <tbody>
          <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
            <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg" , size:"40x40" %></td>
              <td><%= "#{user.name}" %></td>
              <td><%="フォロー数:#{user.follower.count}" %></td>
              <td><%= "フォロワー数:#{user.followed.count}" %></td>
              <td><%= link_to "show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/index.html.erb
  <p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <table class="table">
      <tr><%= render 'users/profile', user: @user %></tr>
      </table>
      <div>
        <%= render 'books/form', {book: @booknew, btn: 'Create Book'} %>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
    <%= render 'users/index', user: @users %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <table class='table'>
        <tr><%= render 'users/profile', user: @user %></tr>
      </table>

      <div>
        <tr><%= render 'books/form', {book: @booknew, btn: 'Create Book'} %></tr>
      </div>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
        <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
          </thead>
            <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40",fallback: "no_image.jpg"%>
            <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </table>
        </tr>
      </table>
    </div>
  </div>
</div>